[package]
name = "opendht"
version = "0.1.0"
authors = ["Sébastien Blin <sebastien.blin@savoirfairelinux.com>"]
edition = "2021"

[dependencies]
libc="0.2"
os_socketaddr="0.2.3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
